"""delete table token

Revision ID: 5dcca7cbde34
Revises: fe4649c4fca2
Create Date: 2022-07-07 13:08:18.697979

"""


# revision identifiers, used by Alembic.
revision = '5dcca7cbde34'
down_revision = 'fe4649c4fca2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
