"""create table device

Revision ID: ae34635ed36d
Revises: 
Create Date: 2022-07-05 11:05:59.958370

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ae34635ed36d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aboutdevice',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('devicetype', sa.Unicode(), nullable=True),
                    sa.Column('manufacture', sa.Unicode(), nullable=True),
                    sa.Column('model', sa.Unicode(), nullable=True),
                    sa.Column('storage', sa.Integer(), nullable=True),
                    sa.Column('grade_a', sa.Float(), nullable=True),
                    sa.Column('grade_b', sa.Float(), nullable=True),
                    sa.Column('grade_c', sa.Float(), nullable=True),
                    sa.Column('grade_d', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aboutdevice')
    # ### end Alembic commands ###
