"""create table access_token

Revision ID: fe4649c4fca2
Revises: c190b70379d2
Create Date: 2022-07-06 16:11:12.019883

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fe4649c4fca2'
down_revision = 'c190b70379d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.Unicode(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_token')
    # ### end Alembic commands ###
